import { ChecklistInput, ManufacturerInfo } from './types'

export const mockManufacturers: ManufacturerInfo[] = [
  {
    name: 'Eagle Carports',
    phone: '(800) 555-0101',
    email: 'orders@eaglecarports.com',
    contactName: 'Mike Reynolds',
  },
  {
    name: 'American Carports',
    phone: '(800) 555-0202',
    email: 'scheduling@americancarports.com',
    contactName: 'Sarah Chen',
  },
  {
    name: 'Coast to Coast Carports',
    phone: '(800) 555-0303',
    email: 'delivery@coasttocoast.com',
    contactName: 'James Walker',
  },
]

export const mockOrders: ChecklistInput[] = [
  {
    orderId: 'mock-001',
    orderNumber: 'BBD-2026-0142',
    customerName: 'John Peterson',
    customerEmail: 'john.peterson@email.com',
    deliveryAddress: '4521 Ranch Road, Austin, TX 78701',
    state: 'Texas',
    foundationType: 'Concrete',
    permitStatus: 'No Permit',
    manufacturer: mockManufacturers[0],
    estimatedDeliveryWeeks: 8,
  },
  {
    orderId: 'mock-002',
    orderNumber: 'BBD-2026-0143',
    customerName: 'Maria Gonzalez',
    customerEmail: 'maria.g@email.com',
    deliveryAddress: '789 Lakeside Dr, Orlando, FL 32801',
    state: 'Florida',
    foundationType: 'Level Ground',
    permitStatus: 'Pulling a Permit',
    drawingType: 'Generic',
    manufacturer: mockManufacturers[1],
    estimatedDeliveryWeeks: 10,
  },
  {
    orderId: 'mock-003',
    orderNumber: 'BBD-2026-0144',
    customerName: 'Robert Williams',
    customerEmail: 'rwilliams@email.com',
    deliveryAddress: '1200 Industrial Blvd, Charlotte, NC 28202',
    state: 'North Carolina',
    foundationType: 'Stem Wall',
    permitStatus: 'Pulling a Permit',
    drawingType: 'As-Built',
    manufacturer: mockManufacturers[2],
    estimatedDeliveryWeeks: 12,
  },
  {
    orderId: 'mock-004',
    orderNumber: 'BBD-2026-0145',
    customerName: 'Lisa Chang',
    customerEmail: 'lisa.chang@email.com',
    deliveryAddress: '332 Valley View Rd, Denver, CO 80202',
    state: 'Colorado',
    foundationType: 'Mixed',
    permitStatus: 'Pulling a Permit',
    drawingType: 'Generic',
    manufacturer: mockManufacturers[0],
    estimatedDeliveryWeeks: 9,
  },
  {
    orderId: 'mock-005',
    orderNumber: 'BBD-2026-0146',
    customerName: 'David Thompson',
    customerEmail: 'dthompson@email.com',
    deliveryAddress: '88 Pine St, Portland, OR 97201',
    state: 'Oregon',
    foundationType: 'Other',
    permitStatus: 'No Permit',
    manufacturer: mockManufacturers[1],
    estimatedDeliveryWeeks: 7,
  },
]
