import { ChecklistInput, ManufacturerInfo } from './types'

export const defaultManufacturers: ManufacturerInfo[] = [
  {
    id: 'eagle-carports',
    name: 'Eagle Carports',
    phone: '(800) 283-2453',
    email: 'orders@eaglecarports.com',
    contactName: 'Eagle Carports Team',
    logoUrl: '/logos/Eagle-Carports.png',
  },
  {
    id: 'asci',
    name: 'ASCI',
    phone: '(800) 555-0102',
    email: 'orders@asci.com',
    contactName: 'ASCI Team',
    logoUrl: '/logos/ASCI.png',
  },
  {
    id: 'best-choice',
    name: 'Best Choice',
    phone: '(800) 555-0103',
    email: 'orders@bestchoice.com',
    contactName: 'Best Choice Team',
    logoUrl: '/logos/Best-Choice.png',
  },
  {
    id: 'premium-steel',
    name: 'Premium Steel',
    phone: '(800) 555-0104',
    email: 'orders@premiumsteel.com',
    contactName: 'Premium Steel Team',
    logoUrl: '/logos/Premium-Steel.png',
  },
  {
    id: 'qms',
    name: 'QMS',
    phone: '(800) 555-0105',
    email: 'orders@qms.com',
    contactName: 'QMS Team',
    logoUrl: '/logos/QMS.png',
  },
  {
    id: 'quality-carports',
    name: 'Quality Carports',
    phone: '(800) 555-0106',
    email: 'orders@qualitycarports.com',
    contactName: 'Quality Carports Team',
    logoUrl: '/logos/Quality-Carports.png',
  },
  {
    id: 'sbs',
    name: 'SBS',
    phone: '(800) 555-0107',
    email: 'orders@sbs.com',
    contactName: 'SBS Team',
    logoUrl: '/logos/SBS.png',
  },
  {
    id: 'safeguard',
    name: 'Safeguard',
    phone: '(800) 555-0108',
    email: 'orders@safeguard.com',
    contactName: 'Safeguard Team',
    logoUrl: '/logos/Safeguard.png',
  },
  {
    id: 'tbs',
    name: 'TBS',
    phone: '(800) 555-0109',
    email: 'orders@tbs.com',
    contactName: 'TBS Team',
    logoUrl: '/logos/TBS.png',
  },
]

export function getDefaultOrders(manufacturers: ManufacturerInfo[]): ChecklistInput[] {
  const mfg = (id: string) => manufacturers.find(m => m.id === id) ?? manufacturers[0]

  return [
    {
      orderId: 'mock-001',
      orderNumber: 'BBD-2026-0142',
      customerName: 'John Peterson',
      customerEmail: 'john.peterson@email.com',
      deliveryAddress: '4521 Ranch Road, Austin, TX 78701',
      state: 'Texas',
      foundationType: 'Concrete',
      permitStatus: 'No Permit',
      manufacturer: mfg('eagle-carports'),
      estimatedDeliveryWeeks: 8,
    },
    {
      orderId: 'mock-002',
      orderNumber: 'BBD-2026-0143',
      customerName: 'Maria Gonzalez',
      customerEmail: 'maria.g@email.com',
      deliveryAddress: '789 Lakeside Dr, Orlando, FL 32801',
      state: 'Florida',
      foundationType: 'Level Ground',
      permitStatus: 'Pulling a Permit',
      drawingType: 'Generic',
      manufacturer: mfg('asci'),
      estimatedDeliveryWeeks: 10,
    },
    {
      orderId: 'mock-003',
      orderNumber: 'BBD-2026-0144',
      customerName: 'Robert Williams',
      customerEmail: 'rwilliams@email.com',
      deliveryAddress: '1200 Industrial Blvd, Charlotte, NC 28202',
      state: 'North Carolina',
      foundationType: 'Stem Wall',
      permitStatus: 'Pulling a Permit',
      drawingType: 'As-Built',
      manufacturer: mfg('best-choice'),
      estimatedDeliveryWeeks: 12,
    },
    {
      orderId: 'mock-004',
      orderNumber: 'BBD-2026-0145',
      customerName: 'Lisa Chang',
      customerEmail: 'lisa.chang@email.com',
      deliveryAddress: '332 Valley View Rd, Denver, CO 80202',
      state: 'Colorado',
      foundationType: 'Mixed',
      permitStatus: 'Pulling a Permit',
      drawingType: 'Generic',
      manufacturer: mfg('premium-steel'),
      estimatedDeliveryWeeks: 9,
    },
    {
      orderId: 'mock-005',
      orderNumber: 'BBD-2026-0146',
      customerName: 'David Thompson',
      customerEmail: 'dthompson@email.com',
      deliveryAddress: '88 Pine St, Portland, OR 97201',
      state: 'Oregon',
      foundationType: 'Other',
      permitStatus: 'No Permit',
      manufacturer: mfg('qms'),
      estimatedDeliveryWeeks: 7,
    },
  ]
}
