import { ChecklistInput, Customer, ManufacturerInfo } from './types'

export const defaultManufacturers: ManufacturerInfo[] = [
  {
    id: 'american-steel',
    name: 'American Steel',
    phone: '1-866-730-9865',
    email: 'orders@americansteelcarports.com',
    contactName: 'American Steel Team',
    logoUrl: '/logos/American-Steel.png',
  },
  {
    id: 'eagle-carports',
    name: 'Eagle Carports',
    phone: '(800) 283-2453',
    email: 'orders@eaglecarports.com',
    contactName: 'Eagle Carports Team',
    logoUrl: '/logos/Eagle-Carports.jpeg',
  },
  {
    id: 'asci',
    name: 'ASCI',
    phone: '(800) 555-0102',
    email: 'orders@asci.com',
    contactName: 'ASCI Team',
    logoUrl: '/logos/ASCI.png',
  },
  {
    id: 'best-choice',
    name: 'Best Choice',
    phone: '(800) 555-0103',
    email: 'orders@bestchoice.com',
    contactName: 'Best Choice Team',
    logoUrl: '/logos/Best-Choice.png',
  },
  {
    id: 'premium-steel',
    name: 'Premium Steel',
    phone: '(800) 555-0104',
    email: 'orders@premiumsteel.com',
    contactName: 'Premium Steel Team',
    logoUrl: '/logos/Premium-Steel.png',
  },
  {
    id: 'qms',
    name: 'QMS',
    phone: '(800) 555-0105',
    email: 'orders@qms.com',
    contactName: 'QMS Team',
    logoUrl: '/logos/QMS.png',
  },
  {
    id: 'quality-carports',
    name: 'Quality Carports',
    phone: '(800) 555-0106',
    email: 'orders@qualitycarports.com',
    contactName: 'Quality Carports Team',
    logoUrl: '/logos/Quality-Carports.png',
  },
  {
    id: 'sbs',
    name: 'SBS',
    phone: '(800) 555-0107',
    email: 'orders@sbs.com',
    contactName: 'SBS Team',
    logoUrl: '/logos/SBS.png',
  },
  {
    id: 'safeguard',
    name: 'Safeguard',
    phone: '(800) 555-0108',
    email: 'orders@safeguard.com',
    contactName: 'Safeguard Team',
    logoUrl: '/logos/Safeguard.png',
  },
  {
    id: 'tbs',
    name: 'TBS',
    phone: '(800) 555-0109',
    email: 'orders@tbs.com',
    contactName: 'TBS Team',
    logoUrl: '/logos/TBS.jpeg',
  },
]

export const defaultCustomers: Customer[] = [
  {
    id: 'cust-demo-001',
    orderNumber: 'BBD-2026-0142',
    name: 'John Peterson',
    email: 'john.peterson@email.com',
    phone: '(512) 555-0147',
    deliveryAddress: '4521 Ranch Road, Austin, TX 78701',
    state: 'Texas',
    foundationType: 'Concrete',
    permitStatus: 'No Permit',
    manufacturerId: 'eagle-carports',
    estimatedDeliveryWeeks: 8,
    checklistStatus: 'Sent',
    notes: '40x60 workshop, customer prefers morning delivery',
    createdAt: '2026-03-28T14:30:00.000Z',
  },
  {
    id: 'cust-demo-002',
    orderNumber: 'BBD-2026-0143',
    name: 'Maria Gonzalez',
    email: 'maria.g@email.com',
    phone: '(407) 555-0298',
    deliveryAddress: '789 Lakeside Dr, Orlando, FL 32801',
    state: 'Florida',
    foundationType: 'Level Ground',
    permitStatus: 'Pulling a Permit',
    drawingType: 'Generic',
    manufacturerId: 'asci',
    estimatedDeliveryWeeks: 10,
    checklistStatus: 'Not Sent',
    notes: 'Permit in progress with Orange County',
    createdAt: '2026-04-01T09:15:00.000Z',
  },
  {
    id: 'cust-demo-003',
    orderNumber: 'BBD-2026-0144',
    name: 'Robert Williams',
    email: 'rwilliams@email.com',
    phone: '(704) 555-0183',
    deliveryAddress: '1200 Industrial Blvd, Charlotte, NC 28202',
    state: 'North Carolina',
    foundationType: 'Stem Wall',
    permitStatus: 'Pulling a Permit',
    drawingType: 'As-Built',
    manufacturerId: 'best-choice',
    estimatedDeliveryWeeks: 12,
    checklistStatus: 'Viewed',
    notes: '50x80 commercial building, engineer stamped drawings required',
    createdAt: '2026-03-15T11:00:00.000Z',
  },
  {
    id: 'cust-demo-004',
    orderNumber: 'BBD-2026-0145',
    name: 'Lisa Chang',
    email: 'lisa.chang@email.com',
    phone: '(303) 555-0421',
    deliveryAddress: '332 Valley View Rd, Denver, CO 80202',
    state: 'Colorado',
    foundationType: 'Mixed',
    permitStatus: 'Pulling a Permit',
    drawingType: 'Generic',
    manufacturerId: 'premium-steel',
    estimatedDeliveryWeeks: 9,
    checklistStatus: 'Sent',
    notes: 'High snow load area, needs reinforced trusses',
    createdAt: '2026-04-05T16:45:00.000Z',
  },
  {
    id: 'cust-demo-005',
    orderNumber: 'BBD-2026-0146',
    name: 'David Thompson',
    email: 'dthompson@email.com',
    phone: '(503) 555-0076',
    deliveryAddress: '88 Pine St, Portland, OR 97201',
    state: 'Oregon',
    foundationType: 'Gravel',
    permitStatus: 'No Permit',
    manufacturerId: 'qms',
    estimatedDeliveryWeeks: 7,
    checklistStatus: 'Not Sent',
    notes: '',
    createdAt: '2026-04-08T08:20:00.000Z',
  },
  {
    id: 'cust-demo-006',
    orderNumber: 'BBD-2026-0150',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@email.com',
    phone: '(615) 555-0339',
    deliveryAddress: '2100 Music Row, Nashville, TN 37203',
    state: 'Tennessee',
    foundationType: 'Concrete',
    permitStatus: 'No Permit',
    manufacturerId: 'american-steel',
    estimatedDeliveryWeeks: 8,
    checklistStatus: 'Viewed',
    notes: '30x40 garage, customer very responsive',
    createdAt: '2026-03-20T13:10:00.000Z',
  },
  {
    id: 'cust-demo-007',
    orderNumber: 'BBD-2026-0155',
    name: 'James Rivera',
    email: 'jrivera@email.com',
    phone: '(210) 555-0512',
    deliveryAddress: '905 Alamo Plaza, San Antonio, TX 78205',
    state: 'Texas',
    foundationType: 'Asphalt',
    permitStatus: 'No Permit',
    manufacturerId: 'safeguard',
    estimatedDeliveryWeeks: 6,
    checklistStatus: 'Sent',
    notes: 'RV cover, needs extra height clearance',
    createdAt: '2026-04-03T10:30:00.000Z',
  },
  {
    id: 'cust-demo-008',
    orderNumber: 'BBD-2026-0161',
    name: 'Karen O\'Brien',
    email: 'kobrien@email.com',
    phone: '(864) 555-0287',
    deliveryAddress: '450 Greenville Hwy, Spartanburg, SC 29301',
    state: 'South Carolina',
    foundationType: 'Level Ground',
    permitStatus: 'Pulling a Permit',
    drawingType: 'Generic',
    manufacturerId: 'sbs',
    estimatedDeliveryWeeks: 11,
    checklistStatus: 'Not Sent',
    notes: 'Waiting on county permit approval, follow up next week',
    createdAt: '2026-04-09T15:00:00.000Z',
  },
]

export function getDefaultOrders(manufacturers: ManufacturerInfo[]): ChecklistInput[] {
  const mfg = (id: string) => manufacturers.find(m => m.id === id) ?? manufacturers[0]

  return [
    {
      orderId: 'mock-001',
      orderNumber: 'BBD-2026-0142',
      customerName: 'John Peterson',
      customerEmail: 'john.peterson@email.com',
      deliveryAddress: '4521 Ranch Road, Austin, TX 78701',
      state: 'Texas',
      foundationType: 'Concrete',
      permitStatus: 'No Permit',
      manufacturer: mfg('eagle-carports'),
      estimatedDeliveryWeeks: 8,
    },
    {
      orderId: 'mock-002',
      orderNumber: 'BBD-2026-0143',
      customerName: 'Maria Gonzalez',
      customerEmail: 'maria.g@email.com',
      deliveryAddress: '789 Lakeside Dr, Orlando, FL 32801',
      state: 'Florida',
      foundationType: 'Level Ground',
      permitStatus: 'Pulling a Permit',
      drawingType: 'Generic',
      manufacturer: mfg('asci'),
      estimatedDeliveryWeeks: 10,
    },
    {
      orderId: 'mock-003',
      orderNumber: 'BBD-2026-0144',
      customerName: 'Robert Williams',
      customerEmail: 'rwilliams@email.com',
      deliveryAddress: '1200 Industrial Blvd, Charlotte, NC 28202',
      state: 'North Carolina',
      foundationType: 'Stem Wall',
      permitStatus: 'Pulling a Permit',
      drawingType: 'As-Built',
      manufacturer: mfg('best-choice'),
      estimatedDeliveryWeeks: 12,
    },
    {
      orderId: 'mock-004',
      orderNumber: 'BBD-2026-0145',
      customerName: 'Lisa Chang',
      customerEmail: 'lisa.chang@email.com',
      deliveryAddress: '332 Valley View Rd, Denver, CO 80202',
      state: 'Colorado',
      foundationType: 'Mixed',
      permitStatus: 'Pulling a Permit',
      drawingType: 'Generic',
      manufacturer: mfg('premium-steel'),
      estimatedDeliveryWeeks: 9,
    },
    {
      orderId: 'mock-005',
      orderNumber: 'BBD-2026-0146',
      customerName: 'David Thompson',
      customerEmail: 'dthompson@email.com',
      deliveryAddress: '88 Pine St, Portland, OR 97201',
      state: 'Oregon',
      foundationType: 'Other',
      permitStatus: 'No Permit',
      manufacturer: mfg('qms'),
      estimatedDeliveryWeeks: 7,
    },
  ]
}
